/** @format */

export const jwtConstants = {
  secret: 'jwtConstants',
};

export const DB = {
  SEQUELIZE: 'SEQUELIZE',
  DATA_SOURCE: 'DATA_SOURCE',
  CAMPAIGN_REPOSITORY: 'CAMPAIGN_REPOSITORY',
  BRIEF_REPOSITORY: 'BRIEF_REPOSITORY',
  RESEARCH_METADATA_REPOSITORY: 'RESEARCH_METADATA_REPOSITORY',
};

export const MONGODB = {
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  EXCHANGE_RATE_MODEL: 'EXCHANGE_RATE_MODEL',
};
